---
- name: Create zend user
  user:
    name: zend
    state: present
    shell: /usr/sbin/nologin

- name: Set zend folder owner
  file:
    path: /home/zend
    owner: zend
    group: zend
    recurse: yes

- name: Clone acme.sh
  git:
    repo: https://github.com/Neilpang/acme.sh.git
    dest: /home/zend/acme.sh
    version: master
  register: acmesh

- name: Install acme.sh
  become_user: zend
  shell: /home/zend/acme.sh/acme.sh --install
  args:
    chdir: /home/zend/acme.sh  
  when: acmesh.changed
  # must re-install acme.sh if we checkout a new release
  # resolves a breaking problem related to a hanging issued fixed in
  # https://github.com/acmesh-official/acme.sh/releases/tag/2.8.3

- name: Allow acme.sh sudo
  lineinfile:
    path: "/etc/sudoers"
    line: 'zend ALL=(ALL) NOPASSWD: /home/zend/.acme.sh/acme.sh,/bin/systemctl restart zend'

- name: Check for certificate
  stat:
    path: "/home/zend/.acme.sh/{{ansible_fqdn}}/{{ansible_fqdn}}.cer"
  register: certificate_exists

- name: Get SSL certificate
  become_user: zend
  shell: "sudo /home/zend/.acme.sh/acme.sh --issue --standalone -d {{ansible_fqdn}} --listen-v6 --renew-hook 'sudo /bin/systemctl restart zend'"
  when: certificate_exists.stat.exists == False

- name: Copy ca.crt
  copy:
    src: /home/zend/.acme.sh/{{ansible_fqdn}}/ca.cer
    dest: /usr/local/share/ca-certificates/ca.crt
    remote_src: yes
  register: ca_cert

# support new LE intermediates as of sept 2020
# https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html
- name: Copy fullchain.crt
  copy:
    src: /home/zend/.acme.sh/{{ansible_fqdn}}/fullchain.cer
    dest: /usr/local/share/ca-certificates/fullchain.crt
    remote_src: yes
  register: fullchain_cert

- name: Update ca-certificates
  shell: "update-ca-certificates --fresh"
  when: ca_cert.changed or fullchain_cert.changed

- name: Remove acme crontab that's missing sudo
  lineinfile:
    path: /var/spool/cron/crontabs/zend
    regexp: \* \"
    state: absent

- name: Remove old crontab line for acme
  lineinfile:
    path: /var/spool/cron/crontabs/zend
    regexp: '^{\d+}'
    line: '\1 0 * * * sudo "/home/zend/.acme.sh"/acme.sh --cron --home "/home/zend/.acme.sh" > /dev/null'
    state: absent

- name: Add sudo to crontab for acme
  lineinfile:
    path: /var/spool/cron/crontabs/zend
    line: '{{ 60 | random(seed=ansible_fqdn) }} 0 * * * sudo "/home/zend/.acme.sh/acme.sh" --cron --home "/home/zend/.acme.sh" --renew-hook "sudo /bin/systemctl restart zend" > /dev/null'
