---
- name: Add key for repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 219F55740BBF7A1CE368BA45FB7053CE4991B669

- name: Add zend repository
  apt_repository:
    repo: deb https://HorizenOfficial.github.io/repo/ focal main
    state: present

- name: Install zend package
  apt:
    name: zen
    state: latest

- name: Check for params folder
  stat:
    path: /home/zend/.zcash-params
  register: params_exists

- name: zen-fetch-params
  shell: zen-fetch-params
  become_user: zend
  when: params_exists.stat.exists == False

- name: Check for zen.conf
  stat:
    path: /home/zend/.zen/zen.conf
  register: zenconf_exists

- name: Initial zend run
  shell: zend
  become_user: zend
  when: zenconf_exists.stat.exists == False
  ignore_errors: true

- name: Copy zend service script
  copy:
    src: zend.service
    dest: /etc/systemd/system/zend.service

- name: Template zen.conf
  template:
    src: zen.conf
    dest: /home/zend/.zen/zen.conf
  register: zen_conf

- name: Start and enable zend
  systemd:
    daemon_reload: yes
    name: zend
    enabled: yes
    state: restarted
  when: zen_conf.changed

- name: Create .zen folder for root
  file:
    path: /root/.zen
    state: directory

- name: Create zen.conf for root
  copy:
    remote_src: yes
    src: /home/zend/.zen/zen.conf
    dest: /root/.zen/zen.conf
