---
- name: Add key for repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 219F55740BBF7A1CE368BA45FB7053CE4991B669

- name: Add zend repository
  apt_repository:
    repo: deb https://HorizenOfficial.github.io/repo/ focal main
    state: present

- name: Install zend package
  apt:
    name: zen
    state: latest

- name: symlink zcash params in from bind mount
  file:
    src: "/mnt"
    dest: "/home/zend/.zcash-params"
    state: link

- name: Check for zen.conf
  stat:
    path: /home/zend/.zen/zen.conf
  register: zenconf_exists

- name: Copy zend service script
  copy:
    src: zend.service
    dest: /etc/systemd/system/zend.service

- name: Template zen.conf
  template:
    src: zen.conf
    dest: /home/zend/.zen/zen.conf
  register: zen_conf

- name: Set perms on blockchain blocks
  file:
    dest=/home/zend/.zen/blocks
    owner=zend
    group=zend
    mode=u=rwX,g=rX,o=r
    recurse=yes

- name: Set perms on blockchain chainstate
  file:
    dest=/home/zend/.zen/chainstate
    owner=zend
    group=zend
    mode=u=rwX,g=rX,o=r
    recurse=yes

- name: Set perms on zen.conf
  file:
    dest=/home/zend/.zen/zen.conf
    owner=zend
    group=zend
    mode=u=rwX,g=rX,o=

- name: Set perms on zen password
  file:
    dest=/home/zend/.zen/.password
    owner=zend
    group=zend
    mode=u=rwX,g=rX,o=

- name: Start and enable zend
  systemd:
    daemon_reload: yes
    name: zend
    enabled: yes
    state: restarted
  when: zen_conf.changed

- name: Create .zen folder for root
  file:
    path: /root/.zen
    state: directory

- name: Create zen.conf for root
  copy:
    remote_src: yes
    src: /home/zend/.zen/zen.conf
    dest: /root/.zen/zen.conf
