---
#- include_tasks: swap.yml
#  tags: swap
- include_tasks: setup.yml
  tags: setup
- include_tasks: ufw.yml
  tags: ufw
- include_tasks: lxcbr0.yml
  tags: lxcbr0
- include_tasks: ssh.yml
  tags: ssh
- include_tasks: rsyslog.yml
  tags: rsyslog
- include_tasks: lxc.yml
  tags: lxc
- include_tasks: blockchain.yml
  tags: blockchain
- include_tasks: zcash-params.yml
  tags: zcash-params
