---
- name: Create .zcash-params folder for root on controller
  file:
    path: /root/.zcash-params
    state: directory

- name: Copy zcash-fetch-params.sh to controller
  copy:
    src: zcash-fetch-params.sh
    dest: /root/.zcash-params/zcash-fetch-params.sh
    owner: root
    group: root
    mode: 0750

- name: Run zcash-fetch-parms on controller
  shell: /root/.zcash-params/zcash-fetch-params.sh